#!/usr/bin/env python3
# compacity-fonts
#
# Copyright 2023 Aleksandar Radivojevic
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# config.py: dynamic configuration file for the font

import psMat
import logging
import collections

from . import Options, generator as g, PROJECT_ROOT, project as p
from builder import font

# returns names of glyphs not file paths
def block(x: str, translate=None):
    '''Transforms a string into list of base glyph names'''
    blocks = []

    top = x[:3]
    middle = x[4:6]
    bottom = x[7:]

    for i in range(3):
        if top[i] != ' ':
            blocks.append(1 + i)

    if middle == '||':
        blocks.append(0)
    else:
        for i in range(2):
            if middle[i] != ' ':
                blocks.append(4 + i)

    for i in range(3):
        if bottom[i] != ' ':
            blocks.append(6 + i)

    return [ g.BBLOCK + str(x) for x in blocks ]

def defaults(glyph: font.GlyphBuilder):
    '''Sets defaults for each glyph, run with GlyphBuilder.do(..)'''
    # glyph.set_unlink_overlap_on_save() \
        # .comment('AUTOGENERATED DO NOT EDIT')
    pass

def check_bounds(glyph: font.GlyphBuilder):
    # for some reason fontforge cant import svg properly and im left with this mess
    # TODO (x, y, w, h) i think check whether width and height are even then
    # try to round it using glyph.round with factor of 0.5 i guess??
    # glyph.glyph.round(0.5) # i am just doing this for now, idk if its will work always
    print(glyph.glyph.glyphname, glyph.glyph.boundingBox())

def gen(font: font.Font, options):
    '''Modified the font'''
    # space width multiplier
    SPACE_MULTI = 1

    if Options.BLOCKSPACE in options:
        SPACE_MULTI = 2

    for i in range(g.BLOCK_COUNT + 1):
        font.glyph().name(g.BBLOCK + str(i)) \
                    .clear() \
                    .do(defaults) \
                    .outline(g.OUTPUT_DIR / g.NAME_FORMAT.format(index=i)) \
                    .width(0) \
                    .color(0xf22929) \
                    .do(check_bounds)

    # remove the line outline to make it invisible in variants
    if Options.NOLINE in options:
        font.glyph().name(g.BBLOCK + '0') \
                    .clear() \
                    .do(defaults) \
                    .width(0) \
                    .color(0xf22929)

    ## LETTERS ##
    LETTERS = {}

    LETTERS['A'] = '  # ||    '
    LETTERS['B'] = '  # || #  '
    LETTERS['C'] = '    || ## '
    LETTERS['D'] = '    ||  # '
    LETTERS['E'] = ' #  ||    '
    LETTERS['F'] = '# # ||    '
    LETTERS['G'] = '    || #  '
    LETTERS['H'] = ' ## || #  '
    LETTERS['I'] = '### || ###'
    LETTERS['J'] = '### || ## '
    LETTERS['K'] = ' #  ||  # '
    LETTERS['L'] = ' ## || ## '
    LETTERS['M'] = '  # || ###'
    LETTERS['N'] = '  # || # #'
    LETTERS['O'] = '#   ||    '
    LETTERS['P'] = '##  ||    '
    LETTERS['Q'] = '#   ||   #'
    LETTERS['R'] = '### ||    '
    LETTERS['S'] = ' ## ||    '
    LETTERS['T'] = '    ||   #'
    LETTERS['U'] = '##  ||  ##'
    LETTERS['V'] = '    ||  ##'
    LETTERS['W'] = '    || ###'
    LETTERS['X'] = '# # || # #'
    LETTERS['Y'] = '# # || ###'
    LETTERS['Z'] = '#   || ###'

    # NOTE: add extra letters here

    # check if there are any duplicate keys just in case
    duplicates = [item for item, count in collections.Counter(LETTERS.values()).items() if count > 1]
    if duplicates:
        logging.warning(f"Duplicate letters found ({len(duplicates)})")

    # uppercase and lowercase letters are gonna be the same
    for key, value in dict(LETTERS).items():
        LETTERS[key.lower()] = value

    for k, v in LETTERS.items():
        font.glyph().char(k) \
                    .clear() \
                    .do(defaults) \
                    .width(g.BLOCK_WIDTH) \
                    .refs(block(v)) \
                    .color(0xd97dfa)

    ## NUMBERS ##
    NUMBERS = {}

    # i used to generate these from binary but it's messy and well it ain't
    # gonna change so why not just predefine it
    NUMBERS['0'] = '#        #'
    NUMBERS['1'] = '#       ##'
    NUMBERS['2'] = '#       # '
    NUMBERS['3'] = '#       ##'
    NUMBERS['4'] = '#      #  '
    NUMBERS['5'] = '#      # #'
    NUMBERS['6'] = '#      ## '
    NUMBERS['7'] = '#      ###'
    NUMBERS['8'] = '#     #   '
    NUMBERS['9'] = '#     #  #'

    for k, v in NUMBERS.items():
        font.glyph().char(k) \
                    .clear() \
                    .do(defaults) \
                    .width(g.BLOCK_WIDTH) \
                    .refs(block(v)) \
                    .color(0x87dbfa)

    # these characters wont be rendered at all
    # TODO maybe add one small character that can indicate that there are
    # useless characters there
    ZERO_WIDTH = r';:-`—@#$%^&*~/\|_=+~`<>'

    for k in ZERO_WIDTH:
        font.glyph().char(k) \
                    .clear() \
                    .do(defaults) \
                    .width(0) \
                    .color(0x3b0f1e)

    ## SYMBOLS ##
    symbol_color = 0xdede59

    font.glyph().char(' ') \
                .clear() \
                .do(defaults) \
                .width(g.BLOCK_WIDTH * 2) \
                .color(symbol_color)

    font.glyph().char('.') \
                .clear() \
                .do(defaults) \
                .refs(block('         #')) \
                .transform(psMat.translate(g.BLOCK_WIDTH, 0)) \
                .width(g.BLOCK_WIDTH * 5) \
                .color(symbol_color)

    font.glyph().char(',') \
                .clear() \
                .do(defaults) \
                .refs(block('        ##')) \
                .transform(psMat.translate(g.BLOCK_WIDTH, 0)) \
                .width(g.BLOCK_WIDTH * 3) \
                .color(symbol_color)

    font.glyph().char('!') \
                .clear() \
                .do(defaults) \
                .refs(block('### ## # #')) \
                .transform(psMat.translate(g.BLOCK_WIDTH, 0)) \
                .width(g.BLOCK_WIDTH * 3) \
                .color(symbol_color)

    font.glyph().char('?') \
                .clear() \
                .do(defaults) \
                .refs(block('# # ## ###')) \
                .transform(psMat.translate(g.BLOCK_WIDTH, 0)) \
                .width(g.BLOCK_WIDTH * 3) \
                .color(symbol_color)

    for i in '“”"‘’\'':
        font.glyph().char(i) \
                    .clear() \
                    .do(defaults) \
                    .refs(block('##         ')) \
                    .transform(psMat.translate(g.BLOCK_WIDTH, 0)) \
                    .width(g.BLOCK_WIDTH * 3) \
                    .color(symbol_color)

    for i in '({[':
        font.glyph().char(i) \
                    .clear() \
                    .do(defaults) \
                    .refs(block('#         ')) \
                    .transform(psMat.translate(g.BLOCK_WIDTH, 0)) \
                    .refs(block('### ## ###')) \
                    .transform(psMat.translate(g.BLOCK_WIDTH, 0)) \
                    .width(g.BLOCK_WIDTH * 4) \
                    .color(symbol_color)

    for i in ')]}':
        font.glyph().char(i) \
                    .clear() \
                    .do(defaults) \
                    .refs(block('### ## ###')) \
                    .transform(psMat.translate(g.BLOCK_WIDTH, 0)) \
                    .refs(block('         #')) \
                    .transform(psMat.translate(g.BLOCK_WIDTH, 0)) \
                    .width(g.BLOCK_WIDTH * 4) \
                    .color(symbol_color)

    if Options.BLOCKSPACE in options:
        # this is the glyph that replaces space in variants with BLOCKSPACE
        font.glyph().name('blockspace') \
                    .clear() \
                    .do(defaults) \
                    .refs(block('    ||    ')) \
                    .transform(psMat.scale(SPACE_MULTI, 1)) \
                    .width(g.BLOCK_WIDTH * SPACE_MULTI) \
                    .comment('This glyph replaces space between letters') \
                    .color(symbol_color)

        font.merge_feature(PROJECT_ROOT / p.FEATURES_DIR / p.FEATURE_BLOCKSPACE)
