suffix = ""
description = ""
formats = ["ttf"]

[options]
line_separator = true
separate_words = false

[glyph]
"A" = { block = "  # ||    " }
"B" = { block = "  # || #  " }
"C" = { block = "    || ## " }
"D" = { block = "    ||  # " }
"E" = { block = " #  ||    " }
"F" = { block = "# # ||    " }
"G" = { block = "    || #  " }
"H" = { block = " ## || #  " }
"I" = { block = "### || ###" }
"J" = { block = "### || ## " }
"K" = { block = " #  ||  # " }
"L" = { block = " ## || ## " }
"M" = { block = "  # || ###" }
"N" = { block = "  # || # #" }
"O" = { block = "#   ||    " }
"P" = { block = "##  ||    " }
"Q" = { block = "#   ||   #" }
"R" = { block = "### ||    " }
"S" = { block = " ## ||    " }
"T" = { block = "    ||   #" }
"U" = { block = "##  ||  ##" }
"V" = { block = "    ||  ##" }
"W" = { block = "    || ###" }
"X" = { block = "# # || # #" }
"Y" = { block = "# # || ###" }
"Z" = { block = "#   || ###" }

"0" = { block = "#        #" }
"1" = { block = "#       ##" }
"2" = { block = "#      # #" }
"3" = { block = "#      ###" }
"4" = { block = "#    #   #" }
"5" = { block = "#    #  ##" }
"6" = { block = "#    # # #" }
"7" = { block = "#    # ###" }
"8" = { block = "#   #    #" }
"9" = { block = "#   #   ##" }

" " = { width = 2 }
"." = { block = [["         #", [1, 0]]], width = 5 }
"," = { block = [["        ##", [1, 0]]], width = 3 }
"!" = { block = [["### ## # #", [1, 0]]], width = 3 }
"?" = { block = [["# # ## ###", [1, 0]]], width = 3 }

'"' = { block = [["##        ", [1, 0]]], width = 3 }

[glyph."("]
width = 4
block = [
    ["#         ", [1, 0]],
    ["### ## ###", [1, 0]],
]

[glyph.")"]
width = 4
block = [
    ["### ## ###", [1, 0]],
    ["         #", [1, 0]],
]

[alias]
zerowidth = ";:-`—@#$%^&*~/\\|_=+~<>"
'"' = "“”‘’'"
"(" = "[{"
")" = "]}"
